### ISSUE TITLE
error trying initializate script

### ISSUE THREAD

**Issue by skyiwii** [RyanPotat/basicTwitchBot#1]
hello, im trying to donwload and use this script, but when a i put "npm start" i see this error:

npm start

> colorchanger@1.0.0 start
> node --no-warnings index.js

file:///home/kai/basicTwitchBot/index.js:3
import config from './config.json' {type: 'json'};
                                   ^

SyntaxError: Unexpected token '{'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
kai@kai-aspiree5573g:~/basicTwitchBot$ 

I dont know what im doing wrong and i would like some help.

**Comment by RyanPotat** [comment]
I would confirm that you have renamed `example-config.json` to `config.json`

and that it conforms to the following format:

``` json
{
    "id": "201109654",
    "username": "skyiwii",
    "twitch_token": "your token",
    "helix_id": "token generator client id",
    "helix_token": "token generator access token",
    "channels": [
        "skyiwii",
        "forsen",
        "xqc"
    ],
    "color_set": "twitch_basic"
}
```

**Comment by skyiwii** [comment]
I was trying to do it on linux since in windows another error was appearing, that says something like "ERR_MODULE_NOT_FOUND", now, i have confirmed that I do all steps correctly and rename the config file just like you said

![Screenshot 2024-01-27 13:57:18](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/babc3975-8da3-48bd-8d38-d5b14da62899)

and the same error is happening again

![Screenshot 2024-01-27 14:00:55](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/bbc33e9b-9055-42e1-ac5e-4e11413443fd)

and this is my config.json file, i put other numbers obviously for the example

![Screenshot 2024-01-27 14:03:28](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/035c3f9e-997c-484f-86bd-debdbfae1233)

**Comment by RyanPotat** [comment]
You may need to update your version of Node.js to a  >16.9.0 version to allow for import assertions for .json files

**Comment by skyiwii** [comment]
Thanks, that was the issue I achieved to run it on Linux, but I have another problem and it's on windows.

The error that appears on windows is this one:

node:internal/modules/esm/resolve:853
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@kararty/dank-twitch-irc' imported from C:\Windows\system32\basicTwitchBot\src\client.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

I thought maybe it was related to the same error and reinstall node to the lastest version but it seems it's not, any ideas? And thank you again for your time 
![image_2024-01-27_231556181](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/11bfd7d5-a2d2-426c-88a5-e8e809e2aaef)

![image_2024-01-27_231657501](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/4745cba0-7790-4d50-8f58-1c896fc8a1d6)

**Comment by RyanPotat** [comment]
run the below command from inside the `basicTwitchBot` directory to install all dependencies in the package.json
```bash
npm install
```

**Comment by skyiwii** [comment]
![image_2024-01-28_160603202](https://github.com/RyanPotat/basicTwitchBot/assets/145174305/56a7c828-53b6-4040-8c87-dc810ac9a83a)

Working now on win and linux, thank you, great script!
